# -*- coding: utf-8 -*-
"""Generate chronology-corrected V3 training and validation cohorts only."""
from __future__ import annotations

import hashlib
import json

import numpy as np

from config import DATA_MAT, OUTPUT_DIR
from v3_data import (
    derive_statistics,
    generate_set,
    metadata_array,
    object_array,
    real_data_splits,
    save_statistics,
)


V3_DIR = OUTPUT_DIR / "v3"
N_TRAIN_NORMAL = 1000
N_VALIDATION_NORMAL = 2000
N_VALIDATION_PER_ANOMALY = 300
TRAIN_SEED = 31001
VALIDATION_NORMAL_SEED = 32001
VALIDATION_ANOMALY_SEED = 33001


def file_sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main():
    V3_DIR.mkdir(exist_ok=True)
    splits = real_data_splits()
    statistics = derive_statistics(splits["stats"])
    statistics.update({
        "split_seed": 123,
        "stats_indices": splits["stats_indices"],
        "holdout_indices": splits["holdout_indices"],
        "source_mat_sha256": file_sha256(DATA_MAT),
    })
    statistics_path = V3_DIR / "sensor_stats_v3.json"
    save_statistics(statistics_path, statistics)

    train = generate_set(
        np.random.default_rng(TRAIN_SEED), statistics,
        N_TRAIN_NORMAL, anomaly=0)
    validation = generate_set(
        np.random.default_rng(VALIDATION_NORMAL_SEED), statistics,
        N_VALIDATION_NORMAL, anomaly=0)
    anomaly_rng = np.random.default_rng(VALIDATION_ANOMALY_SEED)
    validation_anomaly = []
    validation_labels = []
    validation_metadata = []
    for anomaly_type in (1, 2, 3):
        sequences, metadata = generate_set(
            anomaly_rng, statistics, N_VALIDATION_PER_ANOMALY,
            anomaly=anomaly_type, with_metadata=True)
        validation_anomaly.extend(sequences)
        validation_labels.extend([anomaly_type] * len(sequences))
        validation_metadata.extend(metadata)

    data_path = V3_DIR / "selection_data_v3.npz"
    np.savez_compressed(
        data_path,
        X_train=object_array(train),
        X_val=object_array(validation),
        X_val_anom=object_array(validation_anomaly),
        y_val_anom=np.asarray(validation_labels, dtype=np.int64),
        val_metadata=metadata_array(validation_metadata),
        sensor_names=np.asarray(statistics["sensor_names"]),
    )
    protocol = {
        "version": 3,
        "selection_data_only": True,
        "counts": {
            "train_normal": len(train),
            "validation_normal": len(validation),
            "validation_per_anomaly": N_VALIDATION_PER_ANOMALY,
        },
        "seeds": {
            "train_normal": TRAIN_SEED,
            "validation_normal": VALIDATION_NORMAL_SEED,
            "validation_anomaly": VALIDATION_ANOMALY_SEED,
        },
        "chronology_repair": (
            "sort monitored samples by Time and average duplicate timestamps"),
        "normal_distribution": (
            "stats-only recipe groups split at the largest Pressure-mean gap; "
            "each group has an independently phase-aligned profile and noise"),
        "anomaly_protocol": statistics["anomaly_protocol"],
        "data_sha256": file_sha256(data_path),
        "statistics_sha256": file_sha256(statistics_path),
        "holdout_policy": (
            "No V3 test/holdout sequences are generated by this script."),
    }
    protocol_path = V3_DIR / "data_protocol_v3.json"
    protocol_path.write_text(
        json.dumps(protocol, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8")
    print(json.dumps(protocol, ensure_ascii=False, indent=2))
    print(f"Statistics saved: {statistics_path}")
    print(f"Selection data saved: {data_path}")


if __name__ == "__main__":
    main()
